"""add campo cpf ao autor

Revision ID: 701529f7c398
Revises: b96ec39a5a53
Create Date: 2025-06-06 11:43:59.753427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701529f7c398'
down_revision: Union[str, None] = 'b96ec39a5a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autor', sa.Column('cpf', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'autor', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autor', type_='unique')
    op.drop_column('autor', 'cpf')
    # ### end Alembic commands ###
